### ISSUE TITLE
Pb with response and success message does'nt appear

### ISSUE THREAD

**Issue by oitsuki** [zachzurn/MailChimp-Ajax-Signup-Php#1]
Hell,

I inserted your script  and I have an error : 
I change this by that and seems to solve
```
/*
        data = jQuery.parseJSON(response);
*/
        data = response;
```

Also, After to enter an email address and click on the button, no message appear like is I don't insert a good email address.
How to display a message like (success you email is sent).
I think this elment must be change a little bit ???
```
if(data.status != null && data.status == 400 && data.title == "Member Exists"){
          form.addClass('success');
          success();
          console.log('member exists already');
        }
        else if(data.id && data.id.length > 0){
          form.addClass('success');
          success();
          console.log('member added');
        }

```

**Comment by zachzurn** [comment]
You have to use the success class on the form to show a message. For example, form.success span.success{ display:block; }

**Comment by oitsuki** [comment]
Ok thank you : 
I tried two things :
```
<style> 
form.success{ display:block; }
span.success{ display:block; }
</style>
<form name="mailchimp" action="http://....../subscribe.php" method="post" class="success" novalidate="" data-mailchimp="0eba279fdf" data-redirect="http://...../index.php">
```
and `<span class="success"></span>`
but nothing appear (I see in mailchimp the email, it works), but the message when I have no email or wrong email work fine. forgot something ?

I noted also for example that `data-redirect="'. OSCOM::link('index.php?Info&Contact') .'"` does'nt work. maybe the problem is here ?

**Comment by zachzurn** [comment]
This is more how your style should look.

<style> 
form.success span.success{ display:block; }
form span.success{ display:none; }
</style>
